### ISSUE TITLE
validate method mixes extended classes

### ISSUE THREAD

**Issue by darlintonprauchner** [RemyJeancolas/node-typechecker#1]
Given you have:

import {PropertyCheck, validate} from 'node-typechecker';

class AbstractClass {
    @PropertyCheck()
    public abstract_field: string;
}

class ConcreteClass1 extends AbstractClass {
    @PropertyCheck()
    public field1: string;
}

class ConcreteClass2 extends AbstractClass {
    @PropertyCheck()
    public field2: string;
}

 validate({abstract_field:"test", field1:"test"}, ConcreteClass1);

------

_**Will throw an error: "Error: field2: Field is required".
Expected behaviour: Should validate correctly.**_

**Comment by RemyJeancolas** [comment]
@darlintonprauchner should be ok now, [v0.0.8](https://www.npmjs.com/package/node-typechecker) available.
